# Generated by Django 4.2.4 on 2023-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Owner e-mail'),
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
